version: "3.8"
# docker-compose build --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) 
services:
  app:
    ports:
      - '3001:3000'
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfiles/app/Dockerfile
    volumes:
      - ./:/app:rw
    networks:
      - parco-test-network
    depends_on:
      - database
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./db/postgres:/var/lib/postgresql/data:z
    networks:
      - parco-test-network

networks:
  parco-test-network:
